In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore")

In [164]:
from sklearn.datasets import make_classification
X,y =make_classification(n_samples=20,n_features=10,n_clusters_per_class=1,n_redundant=0,n_repeated=0,random_state=1)

In [165]:
X 

array([[-2.02220122,  0.23009474,  1.34849905, -0.30620401,  0.31563495,
         0.76201118, -0.22232814,  0.92733666,  0.82797464, -0.20075807],
       [ 0.61838026, -0.31011677,  0.12766611,  0.23249456,  0.07782113,
        -2.43483776,  1.0388246 , -1.16565058,  0.68255141,  2.18697965],
       [ 0.69803203,  0.40349164,  2.43081444, -0.44712856, -0.62000084,
         0.59357852, -1.09491185,  0.72643387,  1.2245077 ,  0.16938243],
       [ 0.18515642,  0.42349435,  1.22032876, -0.37528495,  1.19891788,
         0.07734007, -0.34385368,  1.02776782, -0.63873041,  0.04359686],
       [ 1.96710175,  1.62765075, -0.45827898, -1.85798186,  1.27375593,
         0.3380117 , -1.19926803,  1.27109482,  1.23616403,  0.86334532],
       [ 0.88514116,  0.51292982,  3.40806982, -0.75439794,  0.28558733,
        -0.29809284,  0.48851815,  0.68622624,  1.25286816, -0.07557171],
       [ 0.41005165, -0.67066229,  3.42278643,  0.19829972,  0.18656139,
         0.37756379,  0.12182127,  0.60113836

In [166]:
y

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1])

In [167]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X ,y,test_size=0.3,random_state=1)

In [168]:
X_train.shape ,X_test.shape

((14, 10), (6, 10))

In [169]:
from sklearn.neighbors import KNeighborsClassifier
clf =KNeighborsClassifier()
clf.fit(X_train ,y_train)

KNeighborsClassifier()

In [170]:
y_pred =clf.predict(X_test)

In [171]:
y_pred

array([0, 1, 0, 1, 0, 1])

In [172]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test ,y_pred))

[[3 0]
 [0 3]]


In [173]:
print(accuracy_score(y_test ,y_pred))

1.0


In [174]:
print(classification_report(y_test ,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         3

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6



In [175]:
from sklearn.model_selection import GridSearchCV
param ={"n_neighbors":[1,2,3,4,5],
       "algorithm":["ball_tree","kd_tree"]}

grid_clf =GridSearchCV(estimator=clf ,param_grid=param,cv=5 ,verbose=3)

In [176]:
grid_clf.fit(X_train ,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END algorithm=ball_tree, n_neighbors=1;, score=0.667 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, n_neighbors=1;, score=0.667 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, n_neighbors=1;, score=1.000 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, n_neighbors=1;, score=1.000 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, n_neighbors=1;, score=1.000 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, n_neighbors=2;, score=1.000 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, n_neighbors=2;, score=0.667 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, n_neighbors=2;, score=1.000 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, n_neighbors=2;, score=1.000 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, n_neighbors=2;, score=1.000 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, n_neighbors=3;, score=1.000 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, n_neighbors=3;

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree'],
                         'n_neighbors': [1, 2, 3, 4, 5]},
             verbose=3)

In [177]:
grid_clf.best_score_

1.0

In [178]:
grid_clf.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 4}

In [179]:
clf_best =grid_clf.best_estimator_
y_grd_pred=clf_best.predict(X_test)

In [180]:
accuracy_score(y_test,y_grd_pred)

1.0