In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn import datasets
X ,y =datasets.make_regression(n_samples=1000
                            ,n_informative=10,n_features=20,n_targets=1,random_state=1)

In [3]:
X

array([[-0.19538922,  1.36969667, -0.50587926, ..., -0.66000264,
        -0.44317197,  0.43097259],
       [ 1.16669852,  0.06796577,  1.0694321 , ..., -0.3178402 ,
        -2.53567476,  0.75011664],
       [ 0.980413  , -0.36616596,  0.38516527, ..., -0.95952672,
         1.73290663, -0.40724513],
       ...,
       [ 1.16725916, -0.78949601,  0.41604786, ...,  0.29411903,
         0.50320642,  1.26250734],
       [ 0.37686892, -1.33758656, -0.28153023, ..., -0.65768166,
        -0.56831204,  0.92162538],
       [-0.31943129, -0.70972042, -0.37569112, ..., -1.29015938,
        -0.92090967, -1.82157283]])

In [4]:
y

array([ 4.33736383e+01,  9.80921698e+01, -5.29461432e+01,  1.24059561e+02,
       -3.05210316e+02, -9.80487437e+00,  2.01964458e+02, -1.21041122e+02,
       -1.38846743e+02, -1.09156187e+02, -2.74400048e+01,  8.30287651e+01,
        6.38111847e+01, -1.80676794e+00,  7.16468812e+01,  8.62953717e+01,
        1.04311656e+02,  1.41133424e+02,  4.83061440e+01,  6.90611708e+01,
       -1.04300214e+01,  3.28055354e+02, -1.99372351e+02,  1.27894056e+02,
       -2.92569467e+02, -1.48375155e+02,  2.54159239e+02,  1.78090657e+02,
        2.66668042e+01,  2.59654044e-01,  8.16754493e+01,  2.70162424e+02,
       -1.78485657e+02, -6.76261398e+01,  2.23212194e+02,  1.45728617e+02,
        5.39959223e+01, -5.58447255e+01,  8.08652565e+01,  6.16230609e+01,
        1.73587981e+00, -4.11677726e+01, -4.39148775e+01,  1.69253550e+02,
        1.17674802e+02,  2.26043509e+01,  6.30868622e+01,  3.49187138e+01,
        5.29169441e+01, -6.63159900e+01, -8.16348499e-01,  3.90267729e+02,
       -1.80316227e+02, -

In [5]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X ,y,test_size=0.30,random_state=42)

In [6]:
from sklearn import neighbors
Regressor =neighbors.KNeighborsRegressor()
Regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [7]:
ypred =Regressor.predict(X_test)

In [8]:
ypred

array([-3.49806178e+01,  3.95316670e+01,  8.57506910e+01, -5.66621370e+01,
        9.91958482e+01, -1.98565908e+02, -1.27951950e+02,  2.63149437e+00,
       -1.07033001e+02, -1.79770590e+01, -2.10627470e+01, -1.52315702e+01,
        1.65680149e+02, -1.07159792e+01,  1.33844800e+01, -1.83607173e+02,
       -1.78491678e+00,  8.34726572e+01, -3.55011129e+01, -5.42563310e+00,
       -3.45849090e+01, -5.92294791e+01,  1.51764179e+02, -4.53285216e+01,
        4.58827006e+01,  1.50791125e+01, -1.12420425e+02, -1.68720213e+01,
       -4.19930064e+01,  4.21440698e+01, -1.40125179e+02, -8.53022767e+01,
        1.48738294e+02,  2.49563788e+00,  6.02629941e+01,  1.33919629e+02,
       -1.57376648e+02, -1.20961145e+02,  1.50152944e+02,  1.60136705e+02,
       -6.15104705e+00,  1.46279382e+01, -8.57844044e+01, -6.90274456e+01,
       -1.38685776e+02, -9.17923582e+01, -1.85184070e+00, -5.75523083e+01,
        3.54631468e+01,  1.44021809e+02, -1.11006347e+01, -4.89094904e+01,
        1.16927357e+02, -

In [9]:
from sklearn.metrics import r2_score
print(r2_score(y_test ,ypred))

0.5982522100829226


In [10]:
param ={"n_neighbors":[1,2,3,4,5],
       "algorithm":["ball_tree","kd_tree"]}
from sklearn.model_selection import GridSearchCV
grid_reg =GridSearchCV(estimator=Regressor ,param_grid=param ,cv =5,verbose=3)
grid_reg.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END algorithm=ball_tree, n_neighbors=1;, score=0.164 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, n_neighbors=1;, score=0.213 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, n_neighbors=1;, score=0.346 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, n_neighbors=1;, score=0.406 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, n_neighbors=1;, score=0.214 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, n_neighbors=2;, score=0.524 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, n_neighbors=2;, score=0.468 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, n_neighbors=2;, score=0.501 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, n_neighbors=2;, score=0.544 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, n_neighbors=2;, score=0.476 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, n_neighbors=3;, score=0.581 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, n_neighbors=3;

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree'],
                         'n_neighbors': [1, 2, 3, 4, 5]},
             verbose=3)

In [12]:
grid_reg.best_estimator_

KNeighborsRegressor(algorithm='ball_tree')

In [13]:
grid_reg.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 5}

In [14]:
grid_reg.best_score_

0.6167731616432736